### ISSUE TITLE
Conflicting with momentum extension

### ISSUE THREAD

**Issue by omares** [kozmos/browser-extensions#3]
The freshly introduced "new tab interface" conflicts with the [momentum](https://momentumdash.com/) extension. 

Unfortunatley disabling the "new tab interface" does not help as momentum is not able to replace the new tab page. The default chrome new tab page is shown.

Could you please investigate this?

**Comment by azer** [comment]
Hi Omares

Sorry to hear Kozmos' new tab didn't work for you. Have you tried the minimal mode with wallpaper ?

The problem you explained is caused by Google Chrome's very limited new tab APIs and I can't do anything to fix it unfortunately. I recommend you to disable/enable the Momentum extension (or re-install it after Kozmos) so momemtum will overide Kozmos.

**Comment by omares** [comment]
Thanks for getting back to me. Reinstalling momentum after kozmos helped overruling kozmos. Now i can have the best of both worlds. 😎
